- name: Install epel-release
  yum:
    name: epel-release
    state: latest
    update_cache: yes

- name: Install the latest version of Nginx
  yum:
    name: nginx
    state: latest
    update_cache: yes
